### ISSUE TITLE
Minor comments

### ISSUE THREAD

**Issue by dakusui** [dahatake/SoftwareEngineer-Basic#1]
Long time no see, and thank you for sharing the great material!
大したコメントではありませんが、気がついたところだけ。

p41-45. RAID6はパリティを２つ持つので、どちらかと言えばRAID5に近い類型だと思います。
RAIDのメリット・デメリットを語る上では、容量の効率性も有ったほうがいいかも知れません。
ディスクが4台しかないと、RAID5, RAID6のRAID1に対する優位点が分かりにくいかも。
(RAID5だとデータ=10台,パリティ1台、RAID6だとデータ10台,パリティ2台といった構成が可能です。そうするとRAID6では性能、対故障性、容量効率性のいずれでも、RAID1よりも優位になると思います。RAID5の場合は性能、容量効率性で優位、対故障性で同等。ただし対故障性＝データが失われない最大の故障点の数、パリティの計算は十分に高速な製品の前提)
RAID3って、使ったことないのですが説明が合ってないような気がします・・・。（あまり使われないモードなので、いっそ説明しなくても・・・とも思いました）

p74. 「メモリは不揮発性」→「メモリは揮発性」では

**Comment by dahatake** [comment]
ご指摘ありがとうございます!
可能な限り直しましたー
